[package]
name = "rustfire_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfire_core = { git = "https://github.com/nik-olay-93/rustfire_core.git" }
